sudo: false

language: perl
perl:
   - "5.22"
   - "5.20"
   - "5.20-shrplib"
   - 5.18
   - "5.18-shrplib"
   - 5.16
   - 5.14
   - 5.12
   - "5.10"
   - 5.8

before_install:
   - eval $(curl https://travis-perl.github.io/init) --auto
   - cpanm --notest --quiet Module::Install::CPANfile Module::Install::AuthorTests

notifications:
   irc:
      channels:
         - irc.freenode.org#chupei.pm
